name: Review Entry

on:
  issue_comment:
    types: [created]

env:
  ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
  COMMENT_AUTHOR: ${{ github.event.comment.user.login }}

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
      verified: ${{ steps.verify.outputs.verify }}

    if: ${{ !github.event.issue.pull_request }}

    steps:
    - uses: khan/pull-request-comment-trigger@v1.1.0
      id: check_accept
      with:
        prefix_only: true
        trigger: '!accept'
      env:
        GITHUB_TOKEN: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'
          
    - uses: khan/pull-request-comment-trigger@v1.1.0
      id: check_reject
      with:
        prefix_only: true
        trigger: '!reject'
      env:
        GITHUB_TOKEN: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'
        
    - name: Checkout Indexer
      uses: actions/checkout@v3
      with:
        path: code

    - name: Checkout Index
      uses: actions/checkout@v3
      with:
        repository: geode-sdk/mods
        path: index
        token: '${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}'

    - name: Verify User
      id: verify_user
      shell: bash
      run: |
        echo result=`python3 code/.github/verify.py index $COMMENT_AUTHOR` >> $GITHUB_OUTPUT

    - name: Add Entry
      if: (steps.check_accept.outputs.triggered == 'true')
      id: add_entry
      shell: bash
      run: |
        python3 code/.github/add-entry-new.py index $ISSUE_AUTHOR >> result.txt

        RESULT=$?

        echo issue_output=`cat result.txt` >> $GITHUB_OUTPUT
        if [ $RESULT -eq 0 ]; then
          echo push_entry=YES >> $GITHUB_OUTPUT
          echo close_issue=YES >> $GITHUB_OUTPUT
        elif [ $RESULT -eq 1 ]; then
          echo push_entry=NO >> $GITHUB_OUTPUT
          echo close_issue=YES >> $GITHUB_OUTPUT
        else
          echo push_entry=NO >> $GITHUB_OUTPUT
          echo close_issue=NO >> $GITHUB_OUTPUT
        fi

      env:
        ISSUE_BODY: ${{ github.event.issue.body }}

    - name: Push to index
      shell: bash
      if: (steps.add_entry.outputs.push_entry == 'YES' && steps.verify_user.outputs.result == 'YES' && steps.check_accept.outputs.triggered == 'true')
      working-directory: ${{ github.workspace }}/index
      run: |
        git config --local user.email "${{ secrets.GEODE_BOT_EMAIL }}"
        git config --local user.name "GeodeBot"
        git add -A
        git commit -m "Update from $ISSUE_AUTHOR"
        git remote set-url origin "https://GeodeBot:${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}@github.com/geode-sdk/mods.git"
        git push -u origin main || true
    
    - name: Close Issue
      uses: peter-evans/close-issue@v3
      if: (steps.verify_user.outputs.result == 'YES' && steps.add_entry.outputs.close_issue == 'YES' && (steps.check_reject.outputs.triggered == 'true' || steps.check_accept.outputs.triggered == 'true'))
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: ${{ steps.add_entry.outputs.issue_output }}
        
